apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
        version: "2"
    spec:
      containers:
      - name: node-web-app
        image: jim/node-web-app
        imagePullPolicy: Never