apiVersion: v1
kind: Pod
metadata:
  name: node-web-app
spec:
  volumes:
  - name: tls-certs
    secret:
      secretName: kuard-tls
  containers:
  - name: app
    image: jim/node-web-app
    imagePullPolicy: Never
    volumeMounts:
    - name: tls-certs
      mountPath: "/tls"
      readOnly: true
    env:
    - name: ANOTHER_PARAM
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: another-param
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    ports:
    - containerPort: 8080